---
kind: pipeline
name: default

steps:
- name: prerequisites
  image: golang:latest
  pull: true
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  environment:
    GO111MODULE: "off"

- name: test
  image: golang:latest
  commands:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  environment:
    GO111MODULE: "off"

- name: codecov
  image: robertstettner/drone-codecov
  settings:
    codecov_token:
      from_secret: codecov_token