---
kind: pipeline
name: default

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: test
  image: golang:latest
  commands:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  environment:
    GO111MODULE: "on"

- name: codecov
  image: robertstettner/drone-codecov
  settings:
    codecov_token:
      from_secret: codecov_token